---
# This playbook will install mysql and create db user

- name: install mysql
  apt:
    force: yes
    name: "mysql-server"
    update-cache: yes
    state: latest

- name: install git
  apt:
    force: yes
    name: git
    update-cache: yes
    state: latest

