---
# This playbook will set up mysql user

- name: cancel ip binding
  replace:
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    regexp: "bind-address*=*127.0.0.1"
    replace: "bind-address            = 0.0.0.0"
    
- name: set up user
  command:
    mysql --execute="GRANT ALL PRIVILEGES ON *.* TO '{{ dbusr }}'@'localhost' IDENTIFIED BY '{{ password }}'; FLUSH PRIVILEGES;"
  notify:
    restart mysql
