---
# This playbook will set up mysql user

- name: cancel ip binding
  replace:
    path: "/etc/mysql/mysql.conf.d/mysqld.cnf"
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

- name: Create database user with name 'bob' and password '12345' with all database privileges
  mysql_user:
    name: '{{ dbusr }}'
    password: '{{ password }}'
    priv: '*.*:ALL,GRANT'
    state: present
    host: '%'
  notify:
    restart mysql

#- name: set up user
#  command:
#    mysql --execute="GRANT ALL PRIVILEGES ON *.* TO '{{ dbusr }}'@'localhost' IDENTIFIED BY '{{ password }}';"

#- name: set up user
#  command:
#    mysql --execute="GRANT ALL PRIVILEGES ON *.* TO '{{ dbusr }}'@'%' IDENTIFIED BY '{{ password }}'; 
#  notify:
#    restart mysql
